import akhil_athira_img1a from "./../../assets/tasveer/akhil_athira/01 a.jpg"
import akhil_athira_img1b from "./../../assets/tasveer/akhil_athira/01 b.jpg"
import akhil_athira_img2 from "./../../assets/tasveer/akhil_athira/02.jpg"
import akhil_athira_img3 from "./../../assets/tasveer/akhil_athira/03.jpg"
import akhil_athira_img4 from "./../../assets/tasveer/akhil_athira/04.jpg"
import akhil_athira_img5 from "./../../assets/tasveer/akhil_athira/05.jpg"
import akhil_athira_img6 from "./../../assets/tasveer/akhil_athira/06.jpg"
import akhil_athira_img7 from "./../../assets/tasveer/akhil_athira/07.jpg"
import akhil_athira_img8 from "./../../assets/tasveer/akhil_athira/08.jpg"
import akhil_athira_img9a from "./../../assets/tasveer/akhil_athira/09a.jpg"
import akhil_athira_img9b from "./../../assets/tasveer/akhil_athira/09 b.jpg"
import akhil_athira_img10 from "./../../assets/tasveer/akhil_athira/10.jpg"
import akhil_athira_img11 from "./../../assets/tasveer/akhil_athira/11.jpg"
import akhil_athira_img12 from "./../../assets/tasveer/akhil_athira/12.jpg"
import akhil_athira_img13 from "./../../assets/tasveer/akhil_athira/13.jpg"
import akhil_athira_img14a from "./../../assets/tasveer/akhil_athira/14a.jpg"
import akhil_athira_img14b from "./../../assets/tasveer/akhil_athira/14b.jpg"
import akhil_athira_img15 from "./../../assets/tasveer/akhil_athira/15.jpg"
import akhil_athira_img16 from "./../../assets/tasveer/akhil_athira/16.jpg"
import akhil_athira_img17 from "./../../assets/tasveer/akhil_athira/17.jpg"
import akhil_athira_img18a from "./../../assets/tasveer/akhil_athira/18a.jpg"
import akhil_athira_img18b from "./../../assets/tasveer/akhil_athira/18b.jpg"
import akhil_athira_img19a from "./../../assets/tasveer/akhil_athira/19a.jpg"
import akhil_athira_img19b from "./../../assets/tasveer/akhil_athira/19b.jpg"
import akhil_athira_img20 from "./../../assets/tasveer/akhil_athira/20.jpg"


import hetal_neel_img1 from "./../../assets/tasveer/hetal_neel/01.jpg"
import hetal_neel_img2 from "./../../assets/tasveer/hetal_neel/02.jpg"
import hetal_neel_img3a from "./../../assets/tasveer/hetal_neel/03a.jpg"
import hetal_neel_img3b from "./../../assets/tasveer/hetal_neel/03b.jpg"
import hetal_neel_img4 from "./../../assets/tasveer/hetal_neel/04.jpg"
import hetal_neel_img5 from "./../../assets/tasveer/hetal_neel/05.jpg"
import hetal_neel_img6 from "./../../assets/tasveer/hetal_neel/06.jpg"
import hetal_neel_img7a from "./../../assets/tasveer/hetal_neel/07a.jpg"
import hetal_neel_img7b from "./../../assets/tasveer/hetal_neel/07b.jpg"
import hetal_neel_img8 from "./../../assets/tasveer/hetal_neel/08.jpg"
import hetal_neel_img9 from "./../../assets/tasveer/hetal_neel/09.jpg"
import hetal_neel_img11 from "./../../assets/tasveer/hetal_neel/11.jpg"
import hetal_neel_img12 from "./../../assets/tasveer/hetal_neel/12.jpg"
import hetal_neel_img14 from "./../../assets/tasveer/hetal_neel/14.jpg"
import hetal_neel_img15 from "./../../assets/tasveer/hetal_neel/15.jpg"
import hetal_neel_img16 from "./../../assets/tasveer/hetal_neel/16.jpg"
import hetal_neel_img17a from "./../../assets/tasveer/hetal_neel/17a.jpg"
import hetal_neel_img17b from "./../../assets/tasveer/hetal_neel/17b.jpg"
import hetal_neel_img18 from "./../../assets/tasveer/hetal_neel/18.jpg"
import hetal_neel_img19 from "./../../assets/tasveer/hetal_neel/19.jpg"
import hetal_neel_img20 from "./../../assets/tasveer/hetal_neel/20.jpg"
import hetal_neel_img21 from "./../../assets/tasveer/hetal_neel/21.jpg"
import hetal_neel_img23 from "./../../assets/tasveer/hetal_neel/23.jpg"
import hetal_neel_img24a from "./../../assets/tasveer/hetal_neel/24a.jpg"
import hetal_neel_img24b from "./../../assets/tasveer/hetal_neel/24b.jpg"
import hetal_neel_img25 from "./../../assets/tasveer/hetal_neel/25.jpg"
import hetal_neel_img26 from "./../../assets/tasveer/hetal_neel/26.jpg"
import hetal_neel_img27a from "./../../assets/tasveer/hetal_neel/27a.jpg"
import hetal_neel_img27b from "./../../assets/tasveer/hetal_neel/27a.jpg"
import hetal_neel_img28 from "./../../assets/tasveer/hetal_neel/28.jpg"
import hetal_neel_img29 from "./../../assets/tasveer/hetal_neel/29.jpg"
import hetal_neel_img30 from "./../../assets/tasveer/hetal_neel/30.jpg"
import hetal_neel_img31 from "./../../assets/tasveer/hetal_neel/31.jpg"
import hetal_neel_img32 from "./../../assets/tasveer/hetal_neel/32.jpg"
import hetal_neel_img33a from "./../../assets/tasveer/hetal_neel/33a.jpg"
import hetal_neel_img33b from "./../../assets/tasveer/hetal_neel/33b.jpg"
import hetal_neel_img34 from "./../../assets/tasveer/hetal_neel/34.jpg"
import hetal_neel_img35 from "./../../assets/tasveer/hetal_neel/35.jpg"
import hetal_neel_img36 from "./../../assets/tasveer/hetal_neel/36.jpg"
import hetal_neel_img37 from "./../../assets/tasveer/hetal_neel/37.jpg"
import hetal_neel_img38 from "./../../assets/tasveer/hetal_neel/38.jpg"
import hetal_neel_img39 from "./../../assets/tasveer/hetal_neel/39.jpg"
import hetal_neel_img40 from "./../../assets/tasveer/hetal_neel/40.jpg"
import hetal_neel_img41 from "./../../assets/tasveer/hetal_neel/41.jpg"
import hetal_neel_img42 from "./../../assets/tasveer/hetal_neel/42.jpg"
import hetal_neel_img43 from "./../../assets/tasveer/hetal_neel/43.jpg"
import hetal_neel_img44 from "./../../assets/tasveer/hetal_neel/44.jpg"
import hetal_neel_img45 from "./../../assets/tasveer/hetal_neel/45.jpg"
import hetal_neel_img46 from "./../../assets/tasveer/hetal_neel/46.jpg"
import hetal_neel_img47a from "./../../assets/tasveer/hetal_neel/47a.jpg"
import hetal_neel_img47b from "./../../assets/tasveer/hetal_neel/47b.jpg"
import hetal_neel_img48 from "./../../assets/tasveer/hetal_neel/48.jpg"
import hetal_neel_img49 from "./../../assets/tasveer/hetal_neel/49.jpg"
import hetal_neel_img50 from "./../../assets/tasveer/hetal_neel/50.jpg"
import hetal_neel_img51 from "./../../assets/tasveer/hetal_neel/51.jpg"
import hetal_neel_img52 from "./../../assets/tasveer/hetal_neel/52.jpg"
import hetal_neel_img53a from "./../../assets/tasveer/hetal_neel/53a.jpg"
import hetal_neel_img53b from "./../../assets/tasveer/hetal_neel/53b.jpg"
import hetal_neel_img54a from "./../../assets/tasveer/hetal_neel/54a.jpg"
import hetal_neel_img54b from "./../../assets/tasveer/hetal_neel/54b.jpg"
import hetal_neel_img55 from "./../../assets/tasveer/hetal_neel/55.jpg"
import hetal_neel_img56 from "./../../assets/tasveer/hetal_neel/56.jpg"
import hetal_neel_img57a from "./../../assets/tasveer/hetal_neel/57a.jpg"
import hetal_neel_img57b from "./../../assets/tasveer/hetal_neel/57b.jpg"
import hetal_neel_img58 from "./../../assets/tasveer/hetal_neel/58.jpg"
import hetal_neel_img59 from "./../../assets/tasveer/hetal_neel/59.jpg"
import hetal_neel_img60 from "./../../assets/tasveer/hetal_neel/60.jpg"
import hetal_neel_img61 from "./../../assets/tasveer/hetal_neel/61.jpg"
import hetal_neel_img62a from "./../../assets/tasveer/hetal_neel/62a.jpg"
import hetal_neel_img62b from "./../../assets/tasveer/hetal_neel/62b.jpg"
import hetal_neel_img63 from "./../../assets/tasveer/hetal_neel/63.jpg"
import hetal_neel_img64 from "./../../assets/tasveer/hetal_neel/64.jpg"
import hetal_neel_img65a from "./../../assets/tasveer/hetal_neel/65a.jpg"
import hetal_neel_img65b from "./../../assets/tasveer/hetal_neel/65b.jpg"
import hetal_neel_img66 from "./../../assets/tasveer/hetal_neel/66.jpg"
import hetal_neel_img69 from "./../../assets/tasveer/hetal_neel/69.jpg"
import hetal_neel_img70 from "./../../assets/tasveer/hetal_neel/70.jpg"
import hetal_neel_img71 from "./../../assets/tasveer/hetal_neel/71.jpg"
import hetal_neel_img72 from "./../../assets/tasveer/hetal_neel/72.jpg"
import hetal_neel_img73 from "./../../assets/tasveer/hetal_neel/73.jpg"
import hetal_neel_img75 from "./../../assets/tasveer/hetal_neel/75.jpg"
import hetal_neel_img76 from "./../../assets/tasveer/hetal_neel/76.jpg"
import hetal_neel_img77 from "./../../assets/tasveer/hetal_neel/77.jpg"
import hetal_neel_img78 from "./../../assets/tasveer/hetal_neel/78.jpg"
import hetal_neel_img79 from "./../../assets/tasveer/hetal_neel/79.jpg"
import hetal_neel_img80a from "./../../assets/tasveer/hetal_neel/80a.jpg"
import hetal_neel_img80b from "./../../assets/tasveer/hetal_neel/80b.jpg"
import hetal_neel_img81 from "./../../assets/tasveer/hetal_neel/81.jpg"


import parth_zeel_img1 from "./../../assets/tasveer/parth_zeel/01.jpg"
import parth_zeel_img2 from "./../../assets/tasveer/parth_zeel/02.jpg"
import parth_zeel_img3a from "./../../assets/tasveer/parth_zeel/03a.jpg"
import parth_zeel_img3b from "./../../assets/tasveer/parth_zeel/03b.jpg"
import parth_zeel_img4 from "./../../assets/tasveer/parth_zeel/04.jpg"
import parth_zeel_img5 from "./../../assets/tasveer/parth_zeel/05.jpg"
import parth_zeel_img6 from "./../../assets/tasveer/parth_zeel/06.jpg"
import parth_zeel_img7a from "./../../assets/tasveer/parth_zeel/07a.jpg"
import parth_zeel_img7b from "./../../assets/tasveer/parth_zeel/07b.jpg"
import parth_zeel_img8 from "./../../assets/tasveer/parth_zeel/08.jpg"
import parth_zeel_img9 from "./../../assets/tasveer/parth_zeel/09.jpg"
import parth_zeel_img10 from "./../../assets/tasveer/parth_zeel/10.jpg"
import parth_zeel_img11 from "./../../assets/tasveer/parth_zeel/11.jpg"
import parth_zeel_img12 from "./../../assets/tasveer/parth_zeel/12.jpg"
import parth_zeel_img13 from "./../../assets/tasveer/parth_zeel/13.jpg"
import parth_zeel_img14a from "./../../assets/tasveer/parth_zeel/14a.jpg"
import parth_zeel_img14b from "./../../assets/tasveer/parth_zeel/14b.jpg"
import parth_zeel_img15 from "./../../assets/tasveer/parth_zeel/15.jpg"
import parth_zeel_img16 from "./../../assets/tasveer/parth_zeel/16.jpg"
import parth_zeel_img17a from "./../../assets/tasveer/parth_zeel/17a.jpg"
import parth_zeel_img17b from "./../../assets/tasveer/parth_zeel/17b.jpg"
import parth_zeel_img18 from "./../../assets/tasveer/parth_zeel/18.jpg"
import parth_zeel_img19 from "./../../assets/tasveer/parth_zeel/19.jpg"
import parth_zeel_img20 from "./../../assets/tasveer/parth_zeel/20.jpg"
import parth_zeel_img21 from "./../../assets/tasveer/parth_zeel/21.jpg"
import parth_zeel_img22 from "./../../assets/tasveer/parth_zeel/22.jpg"
import parth_zeel_img24 from "./../../assets/tasveer/parth_zeel/24.jpg"
import parth_zeel_img25 from "./../../assets/tasveer/parth_zeel/25.jpg"
import parth_zeel_img26a from "./../../assets/tasveer/parth_zeel/26a.jpg"
import parth_zeel_img26b from "./../../assets/tasveer/parth_zeel/26b.jpg"
import parth_zeel_img27 from "./../../assets/tasveer/parth_zeel/27.jpg"
import parth_zeel_img28 from "./../../assets/tasveer/parth_zeel/28.jpg"
import parth_zeel_img28a from "./../../assets/tasveer/parth_zeel/28a.jpg"
import parth_zeel_img28b from "./../../assets/tasveer/parth_zeel/28b.jpg"
import parth_zeel_img29a from "./../../assets/tasveer/parth_zeel/29a.jpg"
import parth_zeel_img29b from "./../../assets/tasveer/parth_zeel/29b.jpg"
import parth_zeel_img30 from "./../../assets/tasveer/parth_zeel/30.jpg"
import parth_zeel_img30a from "./../../assets/tasveer/parth_zeel/30a.jpg"
import parth_zeel_img30b from "./../../assets/tasveer/parth_zeel/30b.jpg"
import parth_zeel_img31 from "./../../assets/tasveer/parth_zeel/31.jpg"
import parth_zeel_img33 from "./../../assets/tasveer/parth_zeel/33.jpg"
import parth_zeel_img34 from "./../../assets/tasveer/parth_zeel/34.jpg"
import parth_zeel_img35 from "./../../assets/tasveer/parth_zeel/35.jpg"
import parth_zeel_img36 from "./../../assets/tasveer/parth_zeel/36.jpg"
import parth_zeel_img37 from "./../../assets/tasveer/parth_zeel/37.jpg"
import parth_zeel_img38 from "./../../assets/tasveer/parth_zeel/38.jpg"
import parth_zeel_img39 from "./../../assets/tasveer/parth_zeel/39.jpg"
import parth_zeel_img40 from "./../../assets/tasveer/parth_zeel/40.jpg"
import parth_zeel_img41 from "./../../assets/tasveer/parth_zeel/41.jpg"
import parth_zeel_img42 from "./../../assets/tasveer/parth_zeel/42.jpg"
import parth_zeel_img43 from "./../../assets/tasveer/parth_zeel/43.jpg"
import parth_zeel_img44 from "./../../assets/tasveer/parth_zeel/44.jpg"
import parth_zeel_img45 from "./../../assets/tasveer/parth_zeel/45.jpg"
import parth_zeel_img46 from "./../../assets/tasveer/parth_zeel/46.jpg"
import parth_zeel_img47 from "./../../assets/tasveer/parth_zeel/47.jpg"
import parth_zeel_img48 from "./../../assets/tasveer/parth_zeel/48.jpg"
import parth_zeel_img49 from "./../../assets/tasveer/parth_zeel/49.jpg"
import parth_zeel_img50 from "./../../assets/tasveer/parth_zeel/50.jpg"
import parth_zeel_img51 from "./../../assets/tasveer/parth_zeel/51.jpg"
import parth_zeel_img52 from "./../../assets/tasveer/parth_zeel/52.jpg"
import parth_zeel_img53 from "./../../assets/tasveer/parth_zeel/53.jpg"
import parth_zeel_img54 from "./../../assets/tasveer/parth_zeel/54.jpg"
import parth_zeel_img55 from "./../../assets/tasveer/parth_zeel/55.jpg"
import parth_zeel_img56a from "./../../assets/tasveer/parth_zeel/56a.jpg"
import parth_zeel_img56b from "./../../assets/tasveer/parth_zeel/56b.jpg"
import parth_zeel_img57 from "./../../assets/tasveer/parth_zeel/57.jpg"
import parth_zeel_img58 from "./../../assets/tasveer/parth_zeel/58.jpg"
import parth_zeel_img59 from "./../../assets/tasveer/parth_zeel/59.jpg"
import parth_zeel_img60 from "./../../assets/tasveer/parth_zeel/60.jpg"
import parth_zeel_img61a from "./../../assets/tasveer/parth_zeel/61 a.jpg"
import parth_zeel_img61b from "./../../assets/tasveer/parth_zeel/61 b.jpg"

import about01 from "./../../assets/about/About us 01.jpg"
import about02 from "./../../assets/about/About us 02.jpg"
import about03 from "./../../assets/about/About us 03.jpg"
import about04 from "./../../assets/about/About us 04.jpg"

import blog11 from "./../../assets/blog1/HOV00032.jpg"
import blog12 from "./../../assets/blog1/HOV00375.jpg"
import blog13 from "./../../assets/blog1/HOV00378.jpg"
import blog14 from "./../../assets/blog1/HOV00427.jpg"
import blog15 from "./../../assets/blog1/HOV01462.jpg"
import blog16 from "./../../assets/blog1/HOV02005.jpg"



export interface TasveerCouple {
  key: string;
  name1: string;
  name2: string;
  coverImage: string;
  images: string[]
}

export const tasveerImages: TasveerCouple[] = [
  {
    key: "akhil_athira",
    name1: "akhil",
    name2: "athira",
    coverImage: akhil_athira_img1a,
    images: [akhil_athira_img1a, akhil_athira_img1b, akhil_athira_img2, akhil_athira_img3, akhil_athira_img4, akhil_athira_img5, akhil_athira_img6, akhil_athira_img7, akhil_athira_img8, akhil_athira_img9a, akhil_athira_img9b, akhil_athira_img10, akhil_athira_img11, akhil_athira_img12, akhil_athira_img13, akhil_athira_img14a, akhil_athira_img14b, akhil_athira_img15, akhil_athira_img16, akhil_athira_img17, akhil_athira_img18a, akhil_athira_img18b, akhil_athira_img19a, akhil_athira_img19b, akhil_athira_img20]
  },
  {
    key: "hetal_neel",
    name1: "hetal",
    name2: "neel",
    coverImage: hetal_neel_img2,
    images: [hetal_neel_img1, hetal_neel_img2, hetal_neel_img3a, hetal_neel_img3b, hetal_neel_img4, hetal_neel_img5, hetal_neel_img6, hetal_neel_img7a, hetal_neel_img7b, hetal_neel_img8, hetal_neel_img9, hetal_neel_img11, hetal_neel_img12, hetal_neel_img14, hetal_neel_img15, hetal_neel_img16, hetal_neel_img17a, hetal_neel_img17b, hetal_neel_img18, hetal_neel_img19, hetal_neel_img20, hetal_neel_img21, hetal_neel_img23, hetal_neel_img24a, hetal_neel_img24b, hetal_neel_img25, hetal_neel_img26, hetal_neel_img27a, hetal_neel_img27b, hetal_neel_img28, hetal_neel_img29, hetal_neel_img30, hetal_neel_img31, hetal_neel_img32, hetal_neel_img33a, hetal_neel_img33b, hetal_neel_img34, hetal_neel_img35, hetal_neel_img36, hetal_neel_img37, hetal_neel_img38, hetal_neel_img39, hetal_neel_img40, hetal_neel_img41, hetal_neel_img42, hetal_neel_img43, hetal_neel_img44, hetal_neel_img45, hetal_neel_img46, hetal_neel_img47a, hetal_neel_img47b, hetal_neel_img48, hetal_neel_img49, hetal_neel_img50, hetal_neel_img51, hetal_neel_img52, hetal_neel_img53a, hetal_neel_img53b, hetal_neel_img54a, hetal_neel_img54b, hetal_neel_img55, hetal_neel_img56, hetal_neel_img57a, hetal_neel_img57b, hetal_neel_img58, hetal_neel_img59, hetal_neel_img60, hetal_neel_img61, hetal_neel_img62a, hetal_neel_img62b, hetal_neel_img63, hetal_neel_img64, hetal_neel_img65a, hetal_neel_img65b, hetal_neel_img66, hetal_neel_img69, hetal_neel_img70, hetal_neel_img71, hetal_neel_img72, hetal_neel_img73, hetal_neel_img75, hetal_neel_img76, hetal_neel_img77, hetal_neel_img78, hetal_neel_img79, hetal_neel_img80a, hetal_neel_img80b, hetal_neel_img81]
  },
  {
    key: "parth_zeel",
    name1: "parth",
    name2: "zeel",
    coverImage: parth_zeel_img2,
    images: [parth_zeel_img1, parth_zeel_img2, parth_zeel_img3a, parth_zeel_img3b, parth_zeel_img4, parth_zeel_img5, parth_zeel_img6, parth_zeel_img7a, parth_zeel_img7b, parth_zeel_img8, parth_zeel_img9, parth_zeel_img10, parth_zeel_img11, parth_zeel_img12, parth_zeel_img13, parth_zeel_img14a, parth_zeel_img14b, parth_zeel_img15, parth_zeel_img16, parth_zeel_img17a, parth_zeel_img17b, parth_zeel_img18, parth_zeel_img19, parth_zeel_img20, parth_zeel_img21, parth_zeel_img22, parth_zeel_img24, parth_zeel_img25, parth_zeel_img26a, parth_zeel_img26b, parth_zeel_img27, parth_zeel_img28, parth_zeel_img28a, parth_zeel_img28b, parth_zeel_img29a, parth_zeel_img29b, parth_zeel_img30, parth_zeel_img30a, parth_zeel_img30b, parth_zeel_img31, parth_zeel_img33, parth_zeel_img34, parth_zeel_img35, parth_zeel_img36, parth_zeel_img37, parth_zeel_img38, parth_zeel_img39, parth_zeel_img40, parth_zeel_img41, parth_zeel_img42, parth_zeel_img43, parth_zeel_img44, parth_zeel_img45, parth_zeel_img46, parth_zeel_img47, parth_zeel_img48, parth_zeel_img49, parth_zeel_img50, parth_zeel_img51, parth_zeel_img52, parth_zeel_img53, parth_zeel_img54, parth_zeel_img55, parth_zeel_img56a, parth_zeel_img56b, parth_zeel_img57, parth_zeel_img58, parth_zeel_img59, parth_zeel_img60, parth_zeel_img61a, parth_zeel_img61b]
  },
]

export const aboutImages: string[] = [ about01, about02, about03, about04 ]

export const blog01Images: string[] = [ blog11, blog12, blog13, blog14, blog15, blog16 ]